if exists (select * from sys.databases where name = 'THCSDL_N4')
	begin
		use master
		alter database THCSDL_N4 set single_user with rollback immediate
		drop database THCSDL_N4;
	end

CREATE DATABASE THCSDL_N4
GO
USE THCSDL_N4

GO
CREATE TABLE KHACHHANG
 (
    MAKHACHANG CHAR(10) PRIMARY KEY,
    TENCONGTY NVARCHAR(50),
    TENGIAODICH NVARCHAR(50),
    DIACHI NVARCHAR(100),
    EMAIL NVARCHAR(50) UNIQUE CHECK (EMAIL LIKE '[a-z]%@%'),
    DIENTHOAI VARCHAR(11) UNIQUE CHECK (LEN(DIENTHOAI) = 10 OR LEN(DIENTHOAI)=11),
    FAX VARCHAR(15)
);

GO
CREATE TABLE NHANVIEN 
(
    MANHANVIEN CHAR(10) PRIMARY KEY,  
    HO NVARCHAR(50) ,         
    TEN NVARCHAR(50),       
    NGAYSINH DATE CHECK (NGAYSINH < GETDATE()),  
    NGAYLAMVIEC DATE, 
    DIACHI NVARCHAR(100),             
    DIENTHOAI VARCHAR(11) UNIQUE CHECK(DIENTHOAI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' OR DIENTHOAI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'), 
    LUONGCB DECIMAL(10, 2) CHECK (LUONGCB >= 0), 
    PHUCAP DECIMAL(10, 2) CHECK (PHUCAP >= 0),   
);

GO
CREATE TABLE DONDATHANG
 (
    SOHOADON CHAR(10) PRIMARY KEY,
    MAKHACHHANG CHAR(10), --FOREIGN KEY REFERENCES KHACHHANG(MAKHACHANG),
    NGAYDATHANG DATE,
    NGAYGIAOHANG DATE,
    NGAYCHUYENHANG DATE,
    NOIGIAOHANG NVARCHAR(100),
    MANHANVIEN CHAR(10) --FOREIGN KEY REFERENCES NHANVIEN(MANHANVIEN)
);

GO
CREATE TABLE LOAIHANG
(
   MALOAIHANG CHAR(10) PRIMARY KEY,
   TENLOAIHANG NVARCHAR(50)
)

GO
CREATE TABLE NHACUNGCAP
(
   MACONGTY CHAR(10) PRIMARY KEY,
   TENCONGTY NVARCHAR(50),
   TENGIAODICH NVARCHAR(50),
   DIACHI NVARCHAR(50),
   DIENTHOAI VARCHAR(11) UNIQUE CHECK(DIENTHOAI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' 
			OR DIENTHOAI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' AND LEN(DIENTHOAI) = 10	OR LEN(DIENTHOAI) = 11),
   FAX VARCHAR(15),
   EMAIL VARCHAR(50)  CHECK (EMAIL LIKE '[a-z]%@%') UNIQUE
);

GO
CREATE TABLE MATHANG
(
   MAHANG CHAR(10) PRIMARY KEY,
   MACONGTY CHAR(10) ,--FOREIGN KEY REFERENCES NHACUNGCAP(MACONGTY),
   MALOAIHANG CHAR(10),-- FOREIGN KEY REFERENCES LOAIHANG(MALOAIHANG),
   TENHANG NVARCHAR(50) ,
   SOLUONG INT CHECK(SOLUONG>=0),
   DONVITINH NVARCHAR(10),
   GIAHANG DECIMAL(18,5) CHECK(GIAHANG>=0)
);

GO
CREATE TABLE CHITIETDATHANG
 (
    SOHOADON CHAR(10), 
    MAHANG CHAR(10) , 
    GIABAN DECIMAL(10, 2) CHECK(GIABAN >= 0),
    SOLUONG INT CHECK(SOLUONG >= 0),
    MUCGIAMGIA DECIMAL(5, 2) CHECK(MUCGIAMGIA >= 0), 
    -- PRIMARY KEY (SOHOADON, MAHANG),  
    -- FOREIGN KEY (SOHOADON) REFERENCES  DONDATHANG(SOHOADON),  
    -- FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG) 
);

-------------------Chỉnh sửa Tuần 6-----------------
-- Thiết lập mối quan hệ giữa các bảng
-- Văn Minh
ALTER TABLE DONDATHANG
	ADD CONSTRAINT FK_DONDATHANG_KHACHHANG FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHANG)
        ON UPDATE 
            CASCADE
			ON DELETE
            CASCADE
        

ALTER TABLE DONDATHANG
    ADD CONSTRAINT FK_DONDATHANG_NHANVIEN FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
        ON UPDATE 
            CASCADE
        ON DELETE
            CASCADE

ALTER TABLE MATHANG
	ADD CONSTRAINT FK_MATHANG_NHACUNGCAP FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY)
        ON UPDATE 
            CASCADE
        ON DELETE
            CASCADE

ALTER TABLE MATHANG
	ADD CONSTRAINT FK_MATHANG_LOAIHANG FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)
        ON UPDATE 
            CASCADE
        ON DELETE
            CASCADE

ALTER TABLE CHITIETDATHANG
	ADD CONSTRAINT FK_CHITIETDATHANG_MATHANG FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG)
        ON UPDATE 
            CASCADE
        ON DELETE
            CASCADE

ALTER TABLE CHITIETDATHANG
	ADD CONSTRAINT FK_CHITIETDATHANG_DONDATHANG FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON)
        ON UPDATE 
            CASCADE
        ON DELETE
            CASCADE

-- Bổ sung ràng buộc thiết lập giá trị mặc định bằng 1 cho cột SOLUONG và bằng 0 cho cột MUCGIAMGIA trong bảng CHiTIETDATHANG
-- Văn Vũ
 ALTER TABLE CHITIETDATHANG
       ADD  CONSTRAINT DF_CHITIETDATHANG_SOLUONG DEFAULT 1 FOR SOLUONG,
			CONSTRAINT DF_CHITIETDATHANG_MUCGIAMGIA DEFAULT 0 FOR MUCGIAMGIA

-- Bổ Sung cho bảng DONDATHANG ràng buộc kiểm tra ngày giao hàng và ngày chuyển hàng phải sau hoặc bằng với ngày đặt hàng.
-- Quách Tỉnh
ALTER TABLE DONDATHANG
   ADD CONSTRAINT CK_DONDATHANG_NgayGiaoHang CHECK(NgayGiaoHang>=NgayDatHang),
       CONSTRAINT CK_DONDATHANG_NgayChuyenHang  CHECK(NgayChuyenHang>=NgayDatHang),
       CONSTRAINT DF_DONDATHANG_NgayDatHang DEFAULT GETDATE() FOR NgayDatHang

-- Bổ sung ràng buộc cho bảng NHANVIEN để đảm bảo rằng một nhân viên chỉ có thể làm việc tỏng công tu khi đủ 18 tuổi và không quá 60 tuổi
-- Phúc An
ALTER TABLE NhanVien
	ADD CONSTRAINT CK_NhanVien_DoB CHECK (NGAYSINH <= DATEADD(YEAR, -18, GETDATE()) 
									AND NGAYSINH >= DATEADD(YEAR, -60, GETDATE()));